/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoadtestRouteImport } from './routes/loadtest'
import { Route as ScorerRouteImport } from './routes/scorer'
import { Route as TvRouteImport } from './routes/tv'
import { Route as ScorerMatchIdRouteImport } from './routes/scorer_.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadtestRoute = LoadtestRouteImport.update({
  id: '/loadtest',
  path: '/loadtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorerRoute = ScorerRouteImport.update({
  id: '/scorer',
  path: '/scorer',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorerMatchIdRoute = ScorerMatchIdRouteImport.update({
  id: '/scorer_/$matchId',
  path: '/scorer/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/loadtest': typeof LoadtestRoute
  '/scorer': typeof ScorerRoute
  '/tv': typeof TvRoute
  '/scorer/$matchId': typeof ScorerMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/loadtest': typeof LoadtestRoute
  '/scorer': typeof ScorerRoute
  '/tv': typeof TvRoute
  '/scorer/$matchId': typeof ScorerMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/loadtest': typeof LoadtestRoute
  '/scorer': typeof ScorerRoute
  '/tv': typeof TvRoute
  '/scorer_/$matchId': typeof ScorerMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/live' | '/loadtest' | '/scorer' | '/tv' | '/scorer/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live' | '/loadtest' | '/scorer' | '/tv' | '/scorer/$matchId'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/loadtest'
    | '/scorer'
    | '/tv'
    | '/scorer_/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  LoadtestRoute: typeof LoadtestRoute
  ScorerRoute: typeof ScorerRoute
  TvRoute: typeof TvRoute
  ScorerMatchIdRoute: typeof ScorerMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadtest': {
      id: '/loadtest'
      path: '/loadtest'
      fullPath: '/loadtest'
      preLoaderRoute: typeof LoadtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorer': {
      id: '/scorer'
      path: '/scorer'
      fullPath: '/scorer'
      preLoaderRoute: typeof ScorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorer_/$matchId': {
      id: '/scorer_/$matchId'
      path: '/scorer/$matchId'
      fullPath: '/scorer/$matchId'
      preLoaderRoute: typeof ScorerMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  LoadtestRoute: LoadtestRoute,
  ScorerRoute: ScorerRoute,
  TvRoute: TvRoute,
  ScorerMatchIdRoute: ScorerMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
